// Tutorial Triggers
export const TUTORIAL_TRIGGERS = {
  OPEN_ISP_CONNECT: "OPEN_ISP_CONNECT",
  ACCEPT_FIRST_CLIENT: "ACCEPT_FIRST_CLIENT",
  OPEN_ANALYTICS: "OPEN_ANALYTICS",
  OPEN_ORDER_UP: "OPEN_ORDER_UP",
  ORDER_FIRST_SERVER: "ORDER_FIRST_SERVER",
  OPEN_LAYOUT_VIEW: "OPEN_LAYOUT_VIEW",
  PLACE_FIRST_SERVER: "PLACE_FIRST_SERVER",
  OPEN_POWER_MANAGER: "OPEN_POWER_MANAGER",
  POWER_ON_FIRST_SERVER: "POWER_ON_FIRST_SERVER",
  OPEN_DAEMON_MANAGER: "OPEN_DAEMON_MANAGER",
  START_FIRST_DAEMON: "START_FIRST_DAEMON",
  OPEN_TASK_RUNNER: "OPEN_TASK_RUNNER",
  SCHEDULE_FIRST_TASK: "SCHEDULE_FIRST_TASK",
  OPEN_SCRIPT_IDE: "OPEN_SCRIPT_IDE",
  WRITE_FIRST_SCRIPT: "WRITE_FIRST_SCRIPT",
};

// Tutorial UI Targets
export const TUTORIAL_TARGETS = {
  ISP_CONNECT_ICON: "ISP_CONNECT_ICON",
  CLIENT_CONNECT_ICON: "CLIENT_CONNECT_ICON",
  ANALYTICS_ICON: "ANALYTICS_ICON",
  ORDER_UP_ICON: "ORDER_UP_ICON",
  FIRST_SERVER_ORDER_BUTTON: "FIRST_SERVER_ORDER_BUTTON",
  LAYOUT_VIEW_ICON: "LAYOUT_VIEW_ICON",
  FIRST_SERVER_IN_RACK: "FIRST_SERVER_IN_RACK",
  POWER_MANAGER_ICON: "POWER_MANAGER_ICON",
  FIRST_SERVER_POWER_BUTTON: "FIRST_SERVER_POWER_BUTTON",
  DAEMON_MANAGER_ICON: "DAEMON_MANAGER_ICON",
  DAEMON_START_BUTTON: "DAEMON_START_BUTTON",
  TASK_RUNNER_ICON: "TASK_RUNNER_ICON",
  TASK_SCHEDULE_BUTTON: "TASK_SCHEDULE_BUTTON",
  SCRIPT_IDE_ICON: "SCRIPT_IDE_ICON",
  SCRIPT_SAVE_BUTTON: "SCRIPT_SAVE_BUTTON",
};
